
[build]
  publish = "."
  command = "echo 'Static site - no build command needed'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/services"
  to = "/#services"
  status = 301

[[redirects]]
  from = "/seo-services"
  to = "/#services"
  status = 301

# Handle SPA fallback
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Prerender for SEO
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Security settings
[context.production.environment]
  HUGO_ENV = "production"

# Plugins for optimization
[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "netlify-plugin-checklinks"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  
  [plugins.inputs]
    baseUrl = "https://outsourcesu.com"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "bing",
      "yandex"
    ]
